I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1, in script
    image stepfather = Drunk_Stepfather.png
  File "game/script.rpy", line 1, in <module>
    image stepfather = Drunk_Stepfather.png
NameError: name 'Drunk_Stepfather' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1, in script
    image stepfather = Drunk_Stepfather.png
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/ast.py", line 933, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1, in <module>
    image stepfather = Drunk_Stepfather.png
NameError: name 'Drunk_Stepfather' is not defined

macOS-15.1.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Proyecto Final 1.0
Wed Apr 23 14:03:15 2025
