I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 17, in script
    define config.main_menu_background = "Watercolor Map of the Americas.png"
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.main_menu_background is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 17, in script
    define config.main_menu_background = "Watercolor Map of the Americas.png"
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/ast.py", line 2248, in execute
    self.set()
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/ast.py", line 2266, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.main_menu_background is not a known configuration variable.

macOS-15.1.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Proyecto Final 1.0
Fri Apr 25 13:40:19 2025
